# Generated by Django 2.2.6 on 2019-10-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('started_date', models.DateField(auto_now_add=True)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
    ]
